git add *.md
#git add _episodes/*.md
git add _episodes/01-introduction.md
git add _episodes/02-storage-spaces.md
git add _episodes/03-data-management.md
git add _episodes/03.2-UPS.md
git add _episodes/03.3-cvmfs.md
git add _episodes/04-intro-art-larsoft.md
git add _episodes/04.4-mrb.md
git add _episodes/06-larsoft-modify-module.md
#git add _episodes/07-grid-job-submission_al9.md
#git add _episodes/07-grid-job-submission-al9.md
git add _episodes/08-submit-jobs-w-justin.md
git add _episodes/09-grid-batch-debug.md
#git add _episodes/10-closing-remarks.md
git add _includes/*.html
git add *.yml
git add _extras/*.md
git add AUTHORS CITATION 
git add gitadd.sh
